using System.Globalization;
using System.Text;
using System.Text.Json;
using HrDataAnalyzer.Models;
namespace HrDataAnalyzer.Services;
public sealed class DataImportService
{
 public async Task<ImportResult> ImportAsync(Stream stream,string fileName,CancellationToken ct=default){using var reader=new StreamReader(stream,Encoding.UTF8,true,1024,true); var text=await reader.ReadToEndAsync(ct); return Path.GetExtension(fileName).Equals(".json",StringComparison.OrdinalIgnoreCase)?ParseJson(text):ParseCsv(text);}
 public ImportResult ParseJson(string text){try{var values=JsonSerializer.Deserialize<List<JsonElement>>(text,new JsonSerializerOptions{PropertyNameCaseInsensitive=true})??[]; var warnings=new List<string>(); var employees=new List<Employee>(); for(var i=0;i<values.Count;i++){if(TryMap(values[i],i+1,out var e,out var warning))employees.Add(e!); else warnings.Add(warning!);} return new(employees,warnings);}catch(JsonException ex){return new([],[$"Invalid JSON: {ex.Message}"]);}}
 public ImportResult ParseCsv(string text){var rows=ReadRows(text); if(rows.Count==0)return new([], ["The file is empty."]); var headers=rows[0]; var employees=new List<Employee>(); var warnings=new List<string>(); for(int i=1;i<rows.Count;i++){var map=headers.Select((h,j)=>new { h=h.Trim(), j }).ToDictionary(x=>x.h,x=>x.j,StringComparer.OrdinalIgnoreCase); var obj=new Dictionary<string,JsonElement>(); foreach(var pair in map) if(pair.Value<rows[i].Count) obj[pair.Key]=JsonSerializer.SerializeToElement(rows[i][pair.Value]); using var doc=JsonDocument.Parse(JsonSerializer.Serialize(obj)); if(TryMap(doc.RootElement,i+1,out var e,out var w))employees.Add(e!); else warnings.Add(w!);} return new(employees,warnings);}
 static List<List<string>> ReadRows(string text){var result=new List<List<string>>(); var row=new List<string>(); var cell=new StringBuilder(); bool quoted=false; for(int i=0;i<text.Length;i++){char c=text[i]; if(c=='"'){if(quoted&&i+1<text.Length&&text[i+1]=='"'){cell.Append('"');i++;}else quoted=!quoted;}else if(c==','&&!quoted){row.Add(cell.ToString().Trim());cell.Clear();}else if((c=='\n'||c=='\r')&&!quoted){if(c=='\r'&&i+1<text.Length&&text[i+1]=='\n')i++;row.Add(cell.ToString().Trim());cell.Clear();if(row.Any(x=>x.Length>0))result.Add(row);row=[];}else cell.Append(c);} if(cell.Length>0||row.Count>0){row.Add(cell.ToString().Trim());result.Add(row);} return result;}
 static bool TryMap(JsonElement o,int line,out Employee? employee,out string? warning){employee=null;warning=null; string Get(params string[] n){foreach(var name in n)if(o.TryGetProperty(name,out var v))return v.ToString().Trim();return "";} var id=Get("id","employeeId","employee_id");var name=Get("name","employeeName","employee_name");var dept=Get("department","team");var role=Get("role","title","jobTitle");var loc=Get("location","office");var type=Get("employmentType","employment_type","type"); var hire=Get("hireDate","hire_date","startDate");var salary=Get("salary","annualSalary","annual_salary");var perf=Get("performanceScore","performance_score","performance");var active=Get("active","isActive","status"); if(string.IsNullOrWhiteSpace(id)||string.IsNullOrWhiteSpace(name)||string.IsNullOrWhiteSpace(dept)){warning=$"Row {line}: id, name, and department are required.";return false;} if(!DateOnly.TryParse(hire,CultureInfo.InvariantCulture,DateTimeStyles.None,out var date)){warning=$"Row {line}: invalid hire date '{hire}'.";return false;} if(!decimal.TryParse(salary,NumberStyles.Number,CultureInfo.InvariantCulture,out var pay)||pay<0){warning=$"Row {line}: salary must be a non-negative number.";return false;} if(!int.TryParse(perf,NumberStyles.Integer,CultureInfo.InvariantCulture,out var score)||score<0||score>100){warning=$"Row {line}: performance must be between 0 and 100.";return false;} var isActive=!active.Equals("false",StringComparison.OrdinalIgnoreCase)&&!active.Equals("inactive",StringComparison.OrdinalIgnoreCase)&&!active.Equals("0"); employee=new(id,name,dept,string.IsNullOrWhiteSpace(role)?"Unspecified":role,string.IsNullOrWhiteSpace(loc)?"Unspecified":loc,string.IsNullOrWhiteSpace(type)?"Full-time":type,date,pay,score,isActive);return true; }
}
