using System.Text.Json;using HrDataAnalyzer.Models;using HrDataAnalyzer.Services;
var builder=WebApplication.CreateBuilder(args);builder.Services.AddSingleton<DataImportService>();builder.Services.AddSingleton<AnalyticsService>();builder.Services.AddSingleton<ReportService>();builder.Services.AddSingleton<DataStore>();var app=builder.Build();app.UseDefaultFiles();app.UseStaticFiles();
app.MapGet("/api/health",()=>Results.Ok(new{status="ok",utc=DateTime.UtcNow}));
app.MapGet("/api/options",(DataStore s)=>Results.Ok(new{departments=s.Employees.Select(x=>x.Department).Distinct().Order(),locations=s.Employees.Select(x=>x.Location).Distinct().Order(),employmentTypes=s.Employees.Select(x=>x.EmploymentType).Distinct().Order()}));
app.MapGet("/api/employees",(HttpRequest req,DataStore s,AnalyticsService a)=>{var f=Parse(req);var values=a.Filter(s.Employees,f);return Results.Ok(new{items=values,total=values.Count,warnings=s.Warnings});});
app.MapGet("/api/analytics",(HttpRequest req,DataStore s,AnalyticsService a)=>{var values=a.Filter(s.Employees,Parse(req));return Results.Ok(new{summary=a.Summarize(values),distributions=a.Distributions(values)});});
app.MapPost("/api/import",async(HttpRequest req,DataStore s,DataImportService importer)=>{if(!req.HasFormContentType)return Results.BadRequest(new{error="multipart/form-data is required"});var form=await req.ReadFormAsync();var file=form.Files.GetFile("file")??form.Files.FirstOrDefault();if(file is null||file.Length==0)return Results.BadRequest(new{error="Choose a CSV or JSON file."});if(Path.GetExtension(file.FileName) is not (".csv" or ".json"))return Results.BadRequest(new{error="Only CSV and JSON files are supported."});await using var stream=file.OpenReadStream();var result=await importer.ImportAsync(stream,file.FileName,req.HttpContext.RequestAborted);if(result.Employees.Count==0)return Results.BadRequest(new{error="No valid employee records found.",warnings=result.Warnings});s.Replace(result.Employees,result.Warnings);return Results.Ok(new{count=result.Employees.Count,warnings=result.Warnings});});
app.MapPost("/api/reset",(DataStore s)=>{s.Reset();return Results.Ok(new{count=s.Employees.Count});});
app.MapGet("/api/export/{format}",(string format,HttpRequest req,DataStore s,AnalyticsService a,ReportService r)=>{var e=a.Filter(s.Employees,Parse(req));return format.ToLowerInvariant() switch{"csv"=>Results.File(r.Csv(e),"text/csv","hr-report.csv"),"json"=>Results.File(r.Json(e),"application/json","hr-report.json"),"html"=>Results.File(r.Html(e,a.Summarize(e)),"text/html","hr-report.html"),_=>Results.BadRequest(new{error="Format must be csv, json, or html."})};});
app.MapFallbackToFile("index.html");app.Run();
static FilterOptions Parse(HttpRequest r)=>new(r.Query["department"],r.Query["location"],r.Query["employmentType"],bool.TryParse(r.Query["active"],out var x)?x:null,decimal.TryParse(r.Query["minSalary"],out var min)?min:null,decimal.TryParse(r.Query["maxSalary"],out var max)?max:null,r.Query["search"]);
public sealed class DataStore{public IReadOnlyList<Employee> Employees{get;private set;}=Sample();public IReadOnlyList<string> Warnings{get;private set;}=[];public void Replace(IReadOnlyList<Employee> e,IReadOnlyList<string> w){Employees=e;Warnings=w;}public void Reset(){Employees=Sample();Warnings=[];}static List<Employee> Sample()=>new(){new("E001","Aisha Patel","Engineering","Software Engineer","Bengaluru","Full-time",new(2021,3,15),92000,88,true),new("E002","Marcus Chen","Sales","Account Executive","New York","Full-time",new(2022,7,1),78000,76,true),new("E003","Sofia Garcia","People","HR Partner","London","Full-time",new(2019,11,4),85000,92,true),new("E004","Noah Williams","Engineering","Data Analyst","Remote","Contract",new(2023,1,12),65000,71,true),new("E005","Priya Shah","Finance","Financial Analyst","Bengaluru","Full-time",new(2020,5,20),74000,84,false),new("E006","Liam Brown","Sales","Sales Manager","Chicago","Full-time",new(2018,9,10),105000,95,true)};}
